### ISSUE TITLE
Feature: add `-v`/`--verbose` flag which lists files being processed

### ISSUE THREAD

**Issue by dtgriscom** [mmiranda/markdown-index#12]
I'm hitting a segfault, which I presume is due to something strange in one of my markdown files. Having a `-v`/`--verbose` flag which printed out file names as they were parsed would be really helpful in tracking the problem down.

**Comment by mmiranda** [comment]
Your request totally makes sense.

I added a new flag `--debug` here: https://github.com/mmiranda/markdown-index/pull/13
