### ISSUE TITLE
Can I use this in Termux somehow?

### ISSUE THREAD

**Issue by b9Joker108** [mmiranda/markdown-index#16]
Can I use this in Termux somehow?

**Comment by mmiranda** [comment]
@b9Joker108 I've never tried but I don't see why not.

You need to get the correct release for Android https://github.com/mmiranda/markdown-index/releases/tag/v0.1.2 (arm linux maybe?) and run it

**Comment by b9Joker108** [comment]
I got it to work just fine in Termux, with the precompiled Linux.aarm64 binary in the Tarball, you pointed out. I just had to extract the Tarball, make it executable and add it to my Path environment variable. 

It is handy to have, but isn't what I was looking for. I actually want a script, app or mechanism, to generate an index for an archive of markdown files, like a traditional index at the end of a book, that indexes all key words and their locations. Your project, sort of generates a table of contents of an archive of makdown files, which is a kind of index, but not the sort of index, I was seeking.

Thanks for your code anyway!
